export const SET_BOARD = 'SET_BOARD';
export const SET_BOARDS = 'SET_BOARDS';
export const CHANGE_OVERLAY_ARRAY = 'CHANGE_OVERLAY_ARRAY';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const CHANGE_TURN = 'CHANGE_TURN';
export const SET_OPPONENTS = 'SET_OPPONENTS';
export const DELETE_BOARD = 'DELETE_BOARD';
