export const allHeroes = [
{
      "id": "01",
      "name": "Link",
      "hp": 50,
      "attack": 50,
      "defense": 50,
      "sp_atk": 30,
      "sp_def": 50,
      "movement": 6,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "link"
  },
 {
      "id": "02",
      "name": "Cloud",
      "hp": 95,
      "attack": 55,
      "defense": 60,
      "sp_atk": 20,
      "sp_def": 65,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "cloud"
  },
{
      "id": "03",
      "name": "MetaKnight",
      "hp": 40,
      "attack": 55,
      "defense": 30,
      "sp_atk": 20,
      "sp_def": 25,
      "movement": 6,
      "range": {0: 1, 1: 3},
      "fly": true,
      image: "metaknight"
  },
 {
      "id": "04",
      "name": "General",
      "hp": 120,
      "attack": 20,
      "defense": 100,
      "sp_atk": 5,
      "sp_def": 80,
      "movement": 3,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "general"
  },
 {
      "id": "05",
      "name": "Tobi",
      "hp": 45,
      "attack": 50,
      "defense": 40,
      "sp_atk": 55,
      "sp_def": 32,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "tobi"
  },
{
      "id": "06",
      "name": "Midna",
      "hp": 50,
      "attack": 20,
      "defense": 35,
      "sp_atk": 65,
      "sp_def": 40,
      "movement": 4,
      "range": {0: 1, 1: 3},
      "fly": true,
      image: "midna"
  },
{
      "id": "07",
      "name": "Lyn",
      "hp": 50,
      "attack": 100,
      "defense": 45,
      "sp_atk": 30,
      "sp_def": 50,
      "movement": 6,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "lyn"
  },
 {
      "id": "08",
      "name": "Deadpool",
      "hp": 75,
      "attack": 75,
      "defense": 90,
      "sp_atk": 30,
      "sp_def": 65,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "deadpool"
  },
 {
      "id": "09",
      "name": "Shuma Gorath",
      "hp": 70,
      "attack": 55,
      "defense": 49,
      "sp_atk": 55,
      "sp_def": 65,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": true,
      image: "shuma_gorath"
  },
{
      "id": "10",
      "name": "Mewtwo",
      "hp": 45,
      "attack": 30,
      "defense": 35,
      "sp_atk": 190,
      "sp_def": 40,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": true,
      image: "mewtwo"
  },
 {
      "id": "11",
      "name": "Samus",
      "hp": 65,
      "attack": 50,
      "defense": 55,
      "sp_atk": 60,
      "sp_def": 55,
      "movement": 4,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "samus"
  },
 {
      "id": "12",
      "name": "Jirachi",
      "hp": 90,
      "attack": 20,
      "defense": 60,
      "sp_atk": 45,
      "sp_def": 65,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": true,
      image: "jirachi"
  },
{
      "id": "13",
      "name": "Isaac",
      "hp": 50,
      "attack": 60,
      "defense": 49,
      "sp_atk": 30,
      "sp_def": 45,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "isaac"
  },
 {
      "id": "14",
      "name": "Charizard",
      "hp": 40,
      "attack": 50,
      "defense": 45,
      "sp_atk": 120,
      "sp_def": 40,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": true,
      image: "charizard"
  },
{
      "id": "15",
      "name": "Master Chief",
      "hp": 60,
      "attack": 55,
      "defense": 65,
      "sp_atk": 50,
      "sp_def": 65,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "master_chief"
  },
{
      "id": "16",
      "name": "Megaman",
      "hp": 45,
      "attack": 20,
      "defense": 40,
      "sp_atk": 55,
      "sp_def": 50,
      "movement": 5,
      "range": {0: 1, 1: 3},
      "fly": false,
      image: "megaman"
  }

];
