export const allItems = [
  {
    'id': '001',
    'name': 'Armorslayer',
    'buy': '1260',
    'uses': '18',
    'rng': '1',
    'MT': '11',
    'HIT': '80',
    'CRIT': '0',
    'LVL': 'D',
  },
  {
    'id': '002',
    'name': 'Audhulma',
    'buy': '----',
    'uses': '30',
    'rng': '1',
    'MT': '9',
    'HIT': '18',
    'CRIT': '0',
    'LVL': 'S',
  },  
  {
    'id': '003',
    'name': 'Brave Sword',
    'buy': '7500',
    'uses': '30',
    'rng': '1',
    'MT': '18',
    'HIT': '80',
    'CRIT': '0',
    'LVL': 'B',
  },
  {
    'id': '004',
    'name': 'Iron Blade',
    'buy': '980',
    'uses': '18',
    'rng': '1',
    'MT': '1',
    'HIT': '90',
    'CRIT': '30',
    'LVL': 'C',
  },
  {
    'id': '005',
    'name': 'Iron Sword',
    'buy': '480',
    'uses': '5',
    'rng': '18',
    'MT': '11',
    'HIT': '80',
    'CRIT': '5',
    'LVL': 'D',
  },
  {
    'id': '006',
    'name': 'Killing Edge',
    'buy': '640',
    'uses': '18',
    'rng': '2',
    'MT': '7',
    'HIT': '50',
    'CRIT': '0',
    'LVL': 'D',
  },
  {
    'id': '007',
    'name': 'Lancereaver',
    'buy': '1800',
    'uses': '18',
    'rng': '3',
    'MT': '11',
    'HIT': '87',
    'CRIT': '0',
    'LVL': 'C',
  },
  {
    'id': '008',
    'name': 'Light Brand',
    'buy': '1260',
    'uses': '18',
    'rng': '18',
    'MT': '11',
    'HIT': '80',
    'CRIT': '0',
    'LVL': 'D',
  },
  {
    'id': '009',
    'name': 'Poison Sword',
    'buy': '1260',
    'uses': '18',
    'rng': '18',
    'MT': '11',
    'HIT': '80',
    'CRIT': '0',
    'LVL': 'C',
  },
  {
    'id': '010',
    'name': 'Rapier',
    'buy': '1260',
    'uses': '18',
    'rng': '18',
    'MT': '11',
    'HIT': '80',
    'CRIT': '0',
    'LVL': 'C',
  },
  {
    'id': '011',
    'name': 'Rapier',
    'buy': '8000',
    'uses': '40',
    'rng': '2',
    'MT': '9',
    'HIT': '70',
    'CRIT': '0',
    'LVL': 'B',
  },
  {
    'id': '012',
    'name': 'ShadowKiller',
    'buy': '500',
    'uses': '18',
    'rng': '18',
    'MT': '11',
    'HIT': '95',
    'CRIT': '0',
    'LVL': 'B',
  }
  ];                