export const allUnits = {
  {
    'id': '01',
    'name': 'Link',
    'hp': 50,
    'attack': 50,
    'defense': 50,
    'sp_atk': 30,
    'sp_def': 50,
    'movement': 6,
    'range': [1, 3],
    'fly': false
    },
      {
    'id': '02',
    'name': 'Cloud',
    'hp': 95,
    'attack': 55,
    'defense': 60,
    'sp_atk': 20,
    'sp_def': 65,
    'movement': 5,
    'range': [1],
    'fly': false
    },
      {
    'id': '03',
    'name': 'MetaKnight',
    'hp': 40,
    'attack': 55,
    'defense': 30,
    'sp_atk': 20,
    'sp_def': 25,
    'movement': 6,
    'range': [1],
    'fly': true
    },
      {
    'id': '04',
    'name': 'General',
    'hp': 120,
    'attack': 20,
    'defense': 100,
    'sp_atk': 5,
    'sp_def': 80,
    'movement': 3,
    'range': [1],
    'fly': false
    },
      {
    'id': '05',
    'name': 'Tobi',
    'hp': 45,
    'attack': 50,
    'defense': 40,
    'sp_atk': 55,
    'sp_def': 32,
    'movement': 5,
    'range': [1, 3],
    'fly': false
    },
      {
    'id': '06',
    'name': 'Midna',
    'hp': 50,
    'attack': 20,
    'defense': 35,
    'sp_atk': 65,
    'sp_def': 40,
    'movement': 4,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '07',
    'name': 'Lyn',
    'hp': 50,
    'attack': 100,
    'defense': 45,
    'sp_atk': 30,
    'sp_def': 50,
    'movement': 6,
    'range': [1],
    'fly': false
    },
      {
    'id': '08',
    'name': 'Deadpool',
    'hp': 75,
    'attack': 75,
    'defense': 90,
    'sp_atk': 30,
    'sp_def': 65,
    'movement': 5,
    'range': [1, 3],
    'fly': false
    },
      {
    'id': '09',
    'name': 'MeatBoy',
    'hp': 40,
    'attack': 30,
    'defense': 40,
    'sp_atk': 45,
    'sp_def': 65,
    'movement': 6,
    'range': [1, 3],
    'fly': false
    },
    {
    'id': '10',
    'name': 'Shuma Gorath',
    'hp': 70,
    'attack': 55,
    'defense': 49,
    'sp_atk': 55,
    'sp_def': 65,
    'movement': 5,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '1',
    'name': 'Mewtwo',
    'hp': 45,
    'attack': 30,
    'defense': 35,
    'sp_atk': 190,
    'sp_def': 40,
    'movement': 5,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '12',
    'name': 'Samus',
    'hp': 65,
    'attack': 50,
    'defense': 55,
    'sp_atk': 60,
    'sp_def': 55,
    'movement': 4,
    'range': [1, 3],
    'fly': false
    },
      {
    'id': '13',
    'name': 'Jirachi',
    'hp': 90,
    'attack': 20,
    'defense': 60,
    'sp_atk': 45,
    'sp_def': 65,
    'movement': 5,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '14',
    'name': 'Belzemon',
    'hp': 60,
    'attack': 55,
    'defense': 60,
    'sp_atk': 65,
    'sp_def': 65,
    'movement': 4,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '15',
    'name': 'Isaac',
    'hp': 50,
    'attack': 60,
    'defense': 49,
    'sp_atk': 30,
    'sp_def': 45,
    'movement': 5,
    'range': [2   , 3],
    'fly': false
    },
      {
    'id': '16',
    'name': 'Korra',
    'hp': 50,
    'attack': 50,
    'defense': 50,
    'sp_atk': 30,
    'sp_def': 50,
    'movement': 6,
    'range': [1, 3],
    'fly': false
    },
      {
    'id': '17',
    'name': 'Charizard',
    'hp': 40,
    'attack': 50,
    'defense': 45,
    'sp_atk': 120,
    'sp_def': 40,
    'movement': 5,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '18',
    'name': 'Boba Fet',
    'hp': 60,
    'attack': 50,
    'defense': 65,
    'sp_atk': 45,
    'sp_def': 65,
    'movement': 4,
    'range': [1, 3],
    'fly': true
    },
      {
    'id': '19',
    'name': 'Master Chief',
    'hp': 60,
    'attack': 55,
    'defense': 65,
    'sp_atk': 50,
    'sp_def': 65,
    'movement': 5,
    'range': [1, 3],
    'fly': false
    },
          {
    'id': '20',
    'name': 'Estela',
    'hp': 60,
    'attack': 30,
    'defense': 60,
    'sp_atk': 55,
    'sp_def': 65,
    'movement': 4,
    'range': [2, 3],
    'fly': true
    },
      {
    'id': '21',
    'name': 'Vivi',
    'hp': 20,
    'attack': 20,
    'defense': 20,
    'sp_atk': 300,
    'sp_def': 25,
    'movement': 2,
    'range': [1, 3]
    'fly': false
    },
      {
    'id': '22',
    'name': 'Megaman',
    'hp': 45,
    'attack': 20,
    'defense': 40,
    'sp_atk': 55,
    'sp_def': 50,
    'movement': 5,
    'range': [1, 3],
    'fly': false
    }
}
